### ISSUE TITLE
Data annotation

### ISSUE THREAD

**Issue by LiuRicky** [JoseponLee/IntentQA#2]
Thanks for your great work. 

About the Intent-QA pairs. It seems it is a filter process based on NeXT-QA, and no more new annotation is added. Am I understanding this correctly? 

So what is the meaning of "annotation" in "After filtering and annotation, our IntentQA dataset ..." (Sec. 3, Data Statistics, first sentence)? Are there any new annotation added? I might miss something important.

**Comment by JoseponLee** [comment]
Sorry for the late reply. We have updated the README and provided detailed descriptions of the additional annotations in the Dataset section. You can download the annotation file, pre-extracted features, original videos, and model weights by clicking on the links provided.
## **Dataset**

Please download the **pre-computed features** and **original videos** from [here](https://drive.google.com/drive/folders/17xu7AGS1VZ8m9J4MeZEzH2515I9MiAPg?usp=drive_link),

There are 3 folders:

- `Videos`: This directory contains all the original videos of the dataset, named with `video_id`. All videos are in MP4 format.
- `region_feat_n`: This folder contains pre-computed bounding box features.
- `frame_feat`: This folder includes pre-computed frame features.

Please download the **QA annotations** from [here](https://drive.google.com/drive/folders/1dtds2e3ddHQ5YyauwC3d1SiSe_K5F-Xa?usp=drive_link). There are 3 files (```train.csv```,```val.csv```,```test.csv``` ):

In each annotation file, the initial columns follow the same format as in `NExT-QA`. Building upon the `NExT-QA` foundation, we have introduced additional annotations, adding extra columns to the dataset. 

*  `action`, `lemma`, and `lemma_id`: Specifically, we have annotated `action`, `lemma`, and `lemma_id`. These columns highlight actions in the current QA that trigger intentions, either self or others', along with the lemmatized forms of these actions and their corresponding IDs after categorizing them into synonymous groups.

* `id`, `pos_id`, and `neg_id`: Furthermore, in the `train.csv` file, we have also added `id`, `pos_id`, and `neg_id` annotations. The `id` column denotes the row number of the data, while the `pos_id` and `neg_id` columns indicate the row numbers (`id`) of data in the train set that form positive and negative cases, respectively, in relation to the current row's data.
